export interface Campaign {
  id: string
  title: string
  description: string
  category: string
  platform: "gofundme" | "chuffed" | "launchgood" | "paypal" | "gogetfunding" | "zeffy" | "other" | "sadagaat"
  originalUrl: string
  organizer?: string
}

export const campaigns: Campaign[] = [
  // Newest Verified Campaigns
  {
    id: "dominique-artist-sudan",
    title: "Help An Artist Stuck in Sudanese War zone",
    description: "Fundraiser by Dominique Banks",
    category: "Emergency Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofundme.com/f/help-an-artist-stuck-in-sudanese-war-zone",
    organizer: "Dominique Banks",
  },
  {
    id: "sudanese-family-need",
    title: "Help A Sudanese Family In Need!!!",
    description: "Emergency support for a Sudanese family",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/ee296ec5",
  },
  {
    id: "sadagaat-usa",
    title: "Sadagaat USA Emergency Relief",
    description: "Supporting humanitarian efforts through Sadagaat USA",
    category: "Humanitarian Aid",
    platform: "sadagaat",
    originalUrl: "https://sadagaat-usa.org/?form=FUNECCSESWQ&fundraiser=NHAQASCT&member=SFUYEJDJ&utm_source=qr",
  },
  {
    id: "general-sudan-support",
    title: "Sudan Emergency Relief",
    description: "General emergency support for Sudan",
    category: "Emergency Relief",
    platform: "gofundme",
    originalUrl: "https://gofund.me/411bd1f6",
  },

  // Support for Hunger and Basic Needs
  {
    id: "uncle-hamdan-kitchen",
    title: "Uncle Hamdan Omdurman Community Kitchen",
    description: "Supporting community kitchen in Omdurman",
    category: "Food & Nutrition",
    platform: "gogetfunding",
    originalUrl: "https://gogetfunding.com/commuinty-kitchen/",
  },
  {
    id: "chuffed-community-kitchen",
    title: "Support Our Community Kitchen",
    description: "Community kitchen support through Chuffed",
    category: "Food & Nutrition",
    platform: "chuffed",
    originalUrl: "https://chuffed.org/project/118514-support-our-community-kitchen",
  },
  {
    id: "saving-algeneina",
    title: "Saving AlGeneina (helps so many people)",
    description: "Supporting the people of AlGeneina",
    category: "Humanitarian Aid",
    platform: "other",
    originalUrl: "https://t.co/toeyVIDoUF",
  },
  {
    id: "khartoum-aid-kitchen",
    title: "Khartoum Aid Kitchen",
    description: "Fight Hunger in Sudan: The Khartoum Kitchen Appeal",
    category: "Food & Nutrition",
    platform: "gofundme",
    originalUrl:
      "https://www.gofundme.com/f/fight-hunger-in-sudan-the-khartoum-kitchen-appeal?lang=en_US&utm_campaign=fp_sharesheet&utm_medium=customer&utm_source=copy_link",
  },
  {
    id: "omdurman-network-hunger",
    title: "Support Omdurman Network's Fight Against Hunger",
    description: "Supporting Omdurman Network's hunger relief efforts",
    category: "Food & Nutrition",
    platform: "gofundme",
    originalUrl: "https://gofund.me/4a1b0159",
  },
  {
    id: "sennar-families-myadah",
    title: "Urgent Help Needed to Support Families in Sennar, Sudan (Myadah)",
    description: "Emergency support for families in Sennar",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofundme.com/f/urgent-help-needed-to-support-families-in-sennar-sudan",
    organizer: "Myadah",
  },
  {
    id: "displaced-families-food-medicine",
    title: "Help Displaced Sudanese Families Pay for Food and Medicine (Somia Ali)",
    description: "Food and medicine for displaced families",
    category: "Food & Medicine",
    platform: "gofundme",
    originalUrl: "https://gofund.me/6840d58f",
    organizer: "Somia Ali",
  },
  {
    id: "families-impacted-war",
    title: "For Sudan: Help us support families impacted by war",
    description: "Supporting families impacted by war",
    category: "Family Support",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/for-sudan-help-us-feed-families-in-omdurman?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
  },
  {
    id: "khartoum-kitchen-appeal-2",
    title: "Fight Hunger in Sudan: The Khartoum Kitchen Appeal",
    description: "Additional Khartoum Kitchen support",
    category: "Food & Nutrition",
    platform: "gofundme",
    originalUrl: "https://gofund.me/52bf2ca3",
  },

  // Medical and Health Support
  {
    id: "medical-students-sanad",
    title: "Help Medical Students in the Sudan war: Sanad Initiative",
    description: "Supporting medical students through Sanad Initiative",
    category: "Healthcare",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-medical-students-in-the-sudan-war-sanad-initiative?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet&lang=en_GB",
  },
  {
    id: "sudan-children-cancer",
    title: "Help Save Lives in Sudan (Sudan Children's Cancer Organization)",
    description: "Supporting Sudan Children's Cancer Organization",
    category: "Healthcare",
    platform: "gofundme",
    originalUrl: "https://gofund.me/cd73380c",
  },
  {
    id: "sukina-father-cancer",
    title: "Supporting Sukina's Father's Fight Against Cancer",
    description: "Cancer treatment support",
    category: "Healthcare",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/supporting-sukinas-fathers-fight-against-cancer?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet&lang=en_US",
  },
  {
    id: "emergency-fund-refugees",
    title: "Emergency Fund: Medical, Shelter, & Edu (Sudanese Refugees)",
    description: "Emergency fund for Sudanese refugees",
    category: "Refugee Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/0c674d5d",
  },
  {
    id: "sudan-medical-appeal",
    title: "Sudan Emergency Medical Appeal- Help Children & War Victims",
    description: "Medical appeal for children and war victims",
    category: "Healthcare",
    platform: "launchgood",
    originalUrl: "https://launchgood.com/v4/campaign/war_in_sudan_crisis_appeal",
  },
  {
    id: "fah-supporting-sudan",
    title: "FAH Supporting Sudan: A Lifeline in Crisis (Sudanese Hospitals)",
    description: "Supporting Sudanese hospitals",
    category: "Healthcare",
    platform: "gofundme",
    originalUrl: "https://gofund.me/b2aebfab",
  },
  {
    id: "family-relocate-medical",
    title: "Family relocate and medical funds (organized by Modasir)",
    description: "Family relocation and medical support",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/d61a7f1c",
    organizer: "Modasir",
  },
  {
    id: "ahmed-family-escape",
    title: "Emergency aid for Ahmed's family to escape warzone in Sudan",
    description: "Emergency aid for Ahmed's family",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/7f76a31e",
  },
  {
    id: "thomaserena-recover",
    title: "Help ThomaSerena recover from war",
    description: "Recovery support for ThomaSerena",
    category: "Healthcare",
    platform: "gofundme",
    originalUrl: "https://gofund.me/4c1d7282",
  },
  {
    id: "khartoum-aid-collective",
    title: "Khartoum aid collective-emergency response rooms",
    description: "Emergency response rooms in Khartoum",
    category: "Emergency Relief",
    platform: "paypal",
    originalUrl: "https://www.paypal.com/donate/?hosted_button_id=C9GCHUJN37MCG",
  },

  // Education Support
  {
    id: "girl-university-degree",
    title: "Help a girl affected by the war finish her university degree (organized by Rawiaa Ahmed)",
    description: "University education support",
    category: "Education",
    platform: "gofundme",
    originalUrl: "https://gofund.me/13d36750",
    organizer: "Rawiaa Ahmed",
  },
  {
    id: "finish-med-school",
    title: "Finish Med school (organized by Sara Ibrahim)",
    description: "Medical school completion support",
    category: "Education",
    platform: "gofundme",
    originalUrl: "https://gofund.me/7395ae1c",
    organizer: "Sara Ibrahim",
  },
  {
    id: "medical-students-evacuate",
    title: "Help two medical students evacuate Sudan with their family",
    description: "Medical students evacuation support",
    category: "Education",
    platform: "gofundme",
    originalUrl: "https://gofund.me/7894cc51",
  },

  // Support for Families Escaping the War
  {
    id: "ahmed-family-sudan",
    title: "Help Ahmed and his family in Sudan",
    description: "Support for Ahmed's family",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/85f07ff8",
  },
  {
    id: "four-families-escape",
    title: "Help four Sudanese families escape the horrors",
    description: "Supporting four families to escape",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://www.gofundme.com/f/help-four-sudanese-families-escape-the-horrors-of",
  },
  {
    id: "razan-escape-khartoum",
    title: "Help My Family Escape War-Torn Khartoum (Razan)",
    description: "Razan's family evacuation from Khartoum",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/581185fd",
    organizer: "Razan",
  },
  {
    id: "asmaa-family-war",
    title: "Sudan War, Help Asmaa's Family",
    description: "Support for Asmaa's family",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/71c0ba04",
  },
  {
    id: "samira-omer-evacuate",
    title: "Evacuate a family from the war (Samira Omer)",
    description: "Family evacuation support",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/3c4a27d2",
    organizer: "Samira Omer",
  },
  {
    id: "family-six-ongoing",
    title: "The Conflict Is Still Ongoing, Save My Family From The War (family of 6)",
    description: "Support for family of 6",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/the-conflict-is-still-ongoing-save-my-family-from-the-war?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet&lang=en_US",
  },
  {
    id: "rama-haran-flee",
    title: "Help My Family Flee Sudan's War (Rama Haran)",
    description: "Rama Haran's family evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/2819c4fb",
    organizer: "Rama Haran",
  },
  {
    id: "four-sudanese-families",
    title: "Help Sudanese Families escape from war (4 families)",
    description: "Supporting 4 families to escape",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/vwb99n-help-sudanese-families?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet&lang=en_US",
  },
  {
    id: "asala-bombardment",
    title: "Save my family from Bombardment (Asala)",
    description: "Asala's family protection from bombardment",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/64215db0",
    organizer: "Asala",
  },
  {
    id: "refugees-cairo",
    title: "Support for Sudanese Refugees in Cairo",
    description: "Supporting refugees in Cairo",
    category: "Refugee Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/8e7954e9",
  },
  {
    id: "shahd-escape-war",
    title: "Help Shahd escape war in Sudan",
    description: "Shahd's evacuation support",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-shahd-escape-war-in-sudan?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
  },
  {
    id: "mujtaba-family-escape",
    title: "Help Mujtaba's Family Escape the war in Sudan",
    description: "Mujtaba's family evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-mujtabas-family-escape-sudans-war?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet&lang=en_US",
  },
  {
    id: "sai-refugees-escape",
    title: "Help Refugee's escape Sudan Conflict (Sai)",
    description: "Refugee escape support by Sai",
    category: "Refugee Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/04ab680e",
    organizer: "Sai",
  },
  {
    id: "khidir-evacuate-family",
    title: "Help evacuate a family from War Torn Sudan (Khidir Mahmoud)",
    description: "Family evacuation by Khidir Mahmoud",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-evacuate-a-family-from-war-torn-sudan?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet",
    organizer: "Khidir Mahmoud",
  },
  {
    id: "family-seven-safety",
    title: "Help Family in Sudan Find Urgent Safety (family of 7)",
    description: "Urgent safety for family of 7",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/89cb364d",
  },
  {
    id: "rasheed-journey-safety",
    title: "Support the Journey to Safety for a Sudanese Family (Rasheed)",
    description: "Rasheed's family journey to safety",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/4fb56d6d",
    organizer: "Rasheed",
  },
  {
    id: "lillian-family-help",
    title: "Donate to help Lillian's family out",
    description: "Support for Lillian's family",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/a776073a",
  },
  {
    id: "passports-escape-war",
    title: "Passports to escape Sudan's war",
    description: "Passport assistance for evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/rbcy43-passports?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet",
  },
  {
    id: "aalaa-family-safety",
    title: "Help Aalaa's Family Escape to Safety",
    description: "Aalaa's family escape to safety",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/928db7db",
  },
  {
    id: "15-families-darfur",
    title: "Help 15 families evacuate El Fashir, Darfur (Sai)",
    description: "15 families evacuation from Darfur",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/2ab03f4a",
    organizer: "Sai",
  },
  {
    id: "umbada-displaced-families",
    title: "Support the Displaced Families of Sudan (Umbada Community)",
    description: "Supporting displaced families in Umbada",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/227be9e9",
  },
  {
    id: "raouf-family-urgent",
    title: "Urgent Support for Our Family in Sudan (Raouf)",
    description: "Urgent support for Raouf's family",
    category: "Family Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/78189356",
    organizer: "Raouf",
  },
  {
    id: "jameela-family-save",
    title: "Join the effort to save Jameela and her family!",
    description: "Community effort to save Jameela's family",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/join-the-effort-to-save-jameela-and-her-family?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
  },
  {
    id: "elaf-escaping-hell",
    title: "Escaping Hell: A Family's Fight For Survival (Elaf)",
    description: "Elaf's family fight for survival",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/823c1d50",
    organizer: "Elaf",
  },
  {
    id: "abudjana-rebuild",
    title: "Help Abudjana rebuild after war",
    description: "Rebuilding support for Abudjana",
    category: "Reconstruction",
    platform: "gofundme",
    originalUrl: "https://gofund.me/8b31c7c0",
  },
  {
    id: "asjad-family-escape",
    title: "Help Asjad and her Family Escape War in Sudan",
    description: "Asjad's family evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/515efb98",
  },
  {
    id: "sajida-family-escape",
    title: "Help my family escape Sudan's war (Sajida)",
    description: "Sajida's family evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-my-friend-and-hwr-family-scape-the-war-in-sud?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
    organizer: "Sajida",
  },
  {
    id: "dystonia-family-escape",
    title: "Help a Sudanese family escape the war in Sudan (Dystonia)",
    description: "Family evacuation support",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/716f3464",
  },
  {
    id: "eman-home-destroyed",
    title: "Our home bombarded and destroyed (Eman Abdel Rahman)",
    description: "Home reconstruction after bombardment",
    category: "Reconstruction",
    platform: "gofundme",
    originalUrl: "https://gofund.me/23057d11",
    organizer: "Eman Abdel Rahman",
  },

  // Support for Refugees
  {
    id: "refugees-cairo-2",
    title: "Sudanese refugees in Cairo",
    description: "Additional support for refugees in Cairo",
    category: "Refugee Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/5cf5e235",
  },
  {
    id: "abeer-community-stuck",
    title: "Support a Community Stuck In Sudan (Abeer)",
    description: "Community support by Abeer",
    category: "Community Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/621aa61d",
    organizer: "Abeer",
  },
  {
    id: "olala-forests-ethiopia",
    title: "Sudanese refugees stranded in Olala forests, Ethiopia",
    description: "Refugees stranded in Ethiopia forests",
    category: "Refugee Support",
    platform: "gofundme",
    originalUrl: "https://gofundme.com/f/sudanese-refugees-stranded-in-olala-forests-ethiopia",
    organizer: "Bothaina Mustafa Basheer Eltigani",
  },

  // General and Other Support
  {
    id: "amal-women-paypal",
    title: "Help the People of Sudan (Amal for Women)",
    description: "Supporting people through Amal for Women",
    category: "Women's Support",
    platform: "paypal",
    originalUrl: "https://paypal.com/pools/c/95K1GpgLLI",
  },
  {
    id: "sustainable-pads",
    title: "One Million Sustainable Pads Campaign",
    description: "Sustainable menstrual products campaign",
    category: "Women's Health",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/37bp8k7p0o?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
  },
  {
    id: "sudan-relief-general",
    title: "Help Sudan - Sudan Relief",
    description: "General Sudan relief efforts",
    category: "Humanitarian Aid",
    platform: "gofundme",
    originalUrl: "https://gofund.me/c00db836",
  },
  {
    id: "save-el-geneina",
    title: "The Save El Geneina Initiative",
    description: "Initiative to save El Geneina",
    category: "Humanitarian Aid",
    platform: "gofundme",
    originalUrl: "https://gofund.me/7ae3d122",
  },
  {
    id: "safe-passage-mom",
    title: "Safe Passage ممر آمن - Help a mom and her kids escape war!",
    description: "Safe passage for mother and children",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/safe-passage-mmr-amn?utm_medium=customer&utm_source=copy_link&utm_campaign=fp_sharesheet",
  },
  {
    id: "kassab-idp-camp",
    title: "For Sudan: Help support families in Kassab IDP camp",
    description: "Supporting families in IDP camp",
    category: "IDP Support",
    platform: "gofundme",
    originalUrl: "https://gofund.me/48732cef",
  },
  {
    id: "sakina-journey-safety",
    title: "Support Sakina's Family's Journey to Safety",
    description: "Sakina's family journey to safety",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/bdc10e02",
  },
  {
    id: "firdous-evacuate",
    title: "Assist Firdous's Family Evacuate from Sudan",
    description: "Firdous family evacuation assistance",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl: "https://gofund.me/c4a259d9",
  },
  {
    id: "additional-support-twitter",
    title: "Additional Sudan Support Initiative",
    description: "Additional support through social media",
    category: "Humanitarian Aid",
    platform: "other",
    originalUrl: "https://t.co/Rtrxco7Cao",
  },
  {
    id: "musa-family-flee",
    title: "Help a family flee War in Sudan (Musa)",
    description: "Musa's family evacuation",
    category: "Family Evacuation",
    platform: "gofundme",
    originalUrl:
      "https://gofundme.com/f/help-a-family-flee-war?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet",
    organizer: "Musa",
  },
  {
    id: "solidarity-collective-paypal",
    title: "Sudan Solidarity Collective",
    description: "Collective solidarity support",
    category: "Humanitarian Aid",
    platform: "paypal",
    originalUrl: "https://www.paypal.com/donate/?hosted_button_id=8PPJTAX5Z5CMY",
  },
  {
    id: "zeffy-fundraising",
    title: "Sudan Crisis Relief Fundraising",
    description: "Crisis relief through Zeffy platform",
    category: "Humanitarian Aid",
    platform: "zeffy",
    originalUrl: "https://www.zeffy.com/en-CA/fundraising/a14ea68c-6fcd-4136-b320-9cbf826d439d",
  },
]

// Categories for filtering
export const categories = [
  "All",
  "Food & Nutrition",
  "Healthcare",
  "Education",
  "Family Support",
  "Family Evacuation",
  "Refugee Support",
  "Humanitarian Aid",
  "Women's Health",
  "Emergency Relief",
  "Emergency Evacuation",
  "Food & Medicine",
  "Community Support",
  "Reconstruction",
  "IDP Support",
  "Women's Support",
]

// Platforms for filtering
export const platforms = [
  "All",
  "gofundme",
  "chuffed",
  "launchgood",
  "paypal",
  "gogetfunding",
  "zeffy",
  "sadagaat",
  "other",
]
